# disable drone ci because of cloud.drone.io stop working


# kind: pipeline
# type: docker
# name: default

# steps:
# - name: build
#   image: node:alpine
#   commands:
#   - npm ci
#   - npm run build
#   - version=$(node -e "console.log(require('./package.json').version)")
#   - echo -n "$version,latest" > .tags

# - name: publish
#   image: plugins/docker
#   settings:
#     repo: lizheming/drone-doumark
#     username:
#       from_secret: docker_username
#     password:
#       from_secret: docker_password